services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:Odisea123@mysql-db:3306/gran_data_test
    depends_on:
      - mysql-db
    volumes:
      - ./src:/app
    networks:
      - app-network

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Odisea123
      MYSQL_DATABASE: gran_data_test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge