from models import RendimientoModel
from extensiones import db

class RendimientoService:
    @staticmethod
    def agregar_rendimiento(row, jugador_id, partido_id):
        nuevo_rendimiento = RendimientoModel(
                jugador_id=jugador_id,
                partido_id=partido_id,
                minutos_jugados=row['Min'],
                goles=row['Gls'],
                asistencias=row['Ast'],
                goles_penal=row['PK'],
                penales_ejecutados=row['PKatt'],
                remates=row['Sh'],
                remates_arco=row['SoT'],
                xG=row['xG'],
                npxG=row['npxG'],
                ocaciones_creadas=row['SCA'],
                goles_creados=row['GCA'],
                pases_cortos_completados=row['Short-Cmp'],
                pases_cortos_intentados=row['Short-Att'],
                pases_medios_completados=row['Medium-Cmp'],
                pases_medios_intentados=row['Medium-Att'],
                pases_largos_completados=row['Long-Cmp'],
                pases_largos_intentados=row['Long-Att'],
                xAG = row['xAG'],
                xA = row['xA'],
                pases_clave=row['KP'],
                pases_progresivos=row['PrgP'],
                pases_intentados=row['Att'],
                pases_filtrados=row['TB'],
                centros=row['Crs'],
                corners_ejecutados=row['CK'],
                entradas=row['Tackles-Tkl'],
                entradas_ganadas=row['Tackles-TklW'],
                bloqueos=row['Blocks-Blocks'],
                remates_bloqueados=row['Blocks-Sh'],
                pases_bloqueados=row['Blocks-Pass'],
                intercepciones=row['Int'],
                despejes=row['Clr'],
                errores_graves=row['Err'],
                gambetas_intentadas=row['Take-Ons-Att'],
                gambetas_completadas=row['Take-Ons-Succ'],
                traslados=row['Carries-Carries'],
                traslados_progresivos=row['Carries-PrgC'],
                tarjetas_amarillas=row['CrdY'],
                tarjetas_rojas=row['CrdR'],
                doble_amarilla=row['2CrdY'],
                faltas=row['Fls'],
                faltas_ganadas=row['Fld'],
                penales_ganados=row['PKwon'],
                penales_concedidos=row['PKcon'],
                goles_en_contra=row['OG'],
                recuperaciones=row['Recov'],
                duelos_aereos_ganados=row['Aerial Duels-Won'],
                duelos_aereos_perdidos=row['Aerial Duels-Lost'],
                remates_arco_recibidos=row['SoTA'],
                goles_recibidos=row['GA'],
                atajadas=row['Saves'],
                PSxG=row['PSxG'],
                centros_enfrentados=row['Crosses-Opp'],
                centros_atajados=row['Crosses-Stp'],
                puntaje=row['puntaje_modelo'],
                puntaje_total=row['puntaje']
                )
        db.session.add(nuevo_rendimiento)
        db.session.commit()